name = "Metis Presentation"
prefix = "mts"
author = "PhILoX, Timi007"
files = [
    "*.dll",
    "*.so",
    "mod.cpp",
    "README.md",
    "LICENSE",
    "mts_logo_over_small.paa",
    "mts_logo_small.paa",
    "mts_picture.paa",
    "meta.cpp"
]

modname = "Metis_Presentation"
key_name = "mts_presentation_{{version}}"
authority = "mts_presentation_{{version}}-{{git \"id 8\"}}"

prebuild = ["!compile_sqf"]
postbuild = ["!compile_sqf_cleanup"]
releasebuild = [
    "@zip Metis_Presentation_{{semver.major}}.{{semver.minor}}.{{semver.patch}}"
]

[header_exts]
version = "{{git \"id 8\"}}"

# SQF Compilation
[scripts.compile_sqf]
steps_windows = [
    "echo Compile SQF",
    "python tools/compile_sqf.py cleanup build"
]
only_release = true
show_output = true

[scripts.compile_sqf_cleanup]
steps_windows = [
    "echo Compile SQF Cleanup",
    "python tools/compile_sqf.py cleanup"
]
only_release = true
show_output = true
