#define IDD_MAIN_DISPLAY 850210

#define IDC_COMBOBOX 1
#define IDC_BUTTON_START 2
#define IDC_BUTTON_CONTINUE 3
#define IDC_LISTBOX 4


#define IDD_CURRENT_SLIDE_DISPLAY 880210
#define IDD_PREVIEW_NEXT_SLIDE_DISPLAY 890210

#define IDC_DISPLAY_BACKGROUND 1
#define IDC_DISPLAY_PICTURE 2

#define IDC_DISPLAY_PREVIEW_LABEL 3
#define IDC_DISPLAY_PREVIEW_BACKGROUND_LABEL 4
